### ISSUE TITLE
Vector Ben"t" Layer keep properties across projects

### ISSUE THREAD

**Issue by vendelagambill13** [olivierdalang/VectorBender#14]
Really amazing program here! I'm still new to it, but wondering when you save the bent layer and open it in a different project without the original vector bender pins, it moves back to original place. Is there a way around this?

**Comment by olivierdalang** [comment]
Hi,

Not sure I understand your issue correctly.

All layers (bender layer and data layers) are regular QGIS layers (in-memory for the bender layer by default). So, if you save any of them and open it in another project, they should stay as they were saved...

Are you sure you exited edit mode for all layers before closing your project ?
