### ISSUE TITLE
Any plan to port to python 3.6 for QGIS 3.0+?

### ISSUE THREAD

**Issue by denchat** [olivierdalang/VectorBender#15]
Wish this briliant UX become a featured plugin or even official feature!

**Comment by olivierdalang** [comment]
Hi, thanks for the kind words. No plan yet for porting to QGIS 3 as I'm not
using the plugin for any current projects.

But it should be easy to port as the code base is small... I'll be happy to
review if anyone wants to give it a shot.

**Comment by PBrockmann** [comment]
Would be very interested as well to use this plugin in QGIS 3.

**Comment by ntripcevich** [comment]
Yes please!

**Comment by olivierdalang** [comment]
Done through #16 (thanks to @jorgealmerio)
