### ISSUE TITLE
Pyhton error - QGIS 3.4 Maderia

### ISSUE THREAD

**Issue by ludovico85** [olivierdalang/VectorBender#20]
Hi, I have a problem with the trasformation of a point file. I get the following python error:

2019-03-22T18:31:01     WARNING    Traceback (most recent call last):
              File "C:/Users/Ludovico/AppData/Roaming/QGIS/QGIS3\profiles\Ludovico/python/plugins\VectorBender\vectorbender.py", line 182, in run
              newGeom = QgsGeometry.fromPoint( self.transformer.map(p) )
             AttributeError: type object 'QgsGeometry' has no attribute 'fromPoint'

**Comment by jaminmelville** [comment]
I have a pull request open that fixes this issue:

https://github.com/olivierdalang/VectorBender/pull/19

Just waiting for that to be merged in.

**Comment by hpethen** [comment]
I am also dealing with this error.

**Comment by olivierdalang** [comment]
fixed in #19
